### ISSUE TITLE
Design media encoding and exchange protocol

### ISSUE THREAD

**Issue by susliko** [susliko/zumba#1]
1. What video encoding should be used?
2. What audio encoding should be used?
3. How to transmit audio and video from client to server?
4. How to merge multiple audio/video streams on server?
5. How to transmit merged streams to clients?

**Comment by m-malikov** [comment]
Мысли по протоколу пока буду набрасывать сюда и редактировать по мере прояснения.

Кодирование видео по аналогии с GIF (палитра на 256 цветов, для каждого следующего кадра храним только прямоугольную область с изменениями, потом все сжимаем LZW или просто зипуем строку с байтами)

Аудио можно отсылать в сыром формате со сжатием тишины. При плохом соединении можно уменьшать частоту дискретизации и число бит на семпл. 

Пакеты для аудио и видео шлем по udp без повторной отправки. Нумеруем пакеты, на принимающей стороне отбрасываем пакеты, с номером большим, чем у последнего отрисованого. В один будем класть примерно 0.5 секунд аудио или видео.

На сервере для каждого клиента собираем его личный фид: объединяем картинки остальных участников в одну и сливаем все аудио в одну дорожку.

+ Пакетов от сервера идет мало, низкий оверхед 
+ Проще реализация на клиенте, всегда только одно для отрисовки видео и одна дорожка для аудио.
+ На клиенте сильно снижается цпу-нагрузка 
- На сервере вырастает цпу-нагрузка, надо пережимать кучу видосов и аудио.
- Если будем делать выключение аудио/видео для конкретных участников, то оноибудет работать с большой задержкой.

По аналогии с  протоколами RTP/RTPC на другом порту tcp-пакетами сервер и клиент обмениваются  служебной информацией:
- сигнал на повышение/понижение качества 
- чат, если будет 
- что-то еще мб

**Comment by m-malikov** [comment]
Про использование готовых билиотек для WebRTC:

Пока что вижу де потенциальные проблемы:
1. Нужен сертификат, а значит и домен (но на локалхосте можно тестировать)
2. Протокол сигналов (повышение/понижение качества, мьют, и прочие метаданные) не зафиксирован. Предполагается что каждое приложение будет реализовывать свой под свои нужды.

Есть готовые библиотеки на python ([https://github.com/aiortc/aiortc/tree/main/examples/server](https://github.com/aiortc/aiortc/tree/main/examples/server)) и java ([https://github.com/aiortc/aiortc/tree/main/examples/server](https://github.com/devopvoid/webrtc-java)). Для scala не нашел, только для scala-js

Сейчас попробую поднять версию на питоне, с джавой наверное будет сложнее)

**Comment by m-malikov** [comment]
Результат ресерча  по WebRTC:

Основная проблема, которую решает  WebRTC - установление p2p соединения между двумя браузерами. Это довольно сложный процесс, но с нашей архитектурой этого делать вообще не нужно. WebRTC не определяет способ кодирования данных и сигнальный протокол для передачи дополнительных данных. В документации предлагается слать джейсоны через вебсокеты или http. 

Получается, что webRTC не решает наши главные проблемы, но при этом довольно сложно устроен и слабо вяжется с десктопом на скале.

Можно посмотреть в сторону протокола [RTP](https://en.wikipedia.org/wiki/Real-time_Transport_Protocol). Но кажется что популярных библиотек для питона/скалы нет, скорее всего придется писать какие-то обертки над линуксовыми консольными утилитами.

В целом, задача отправки и приёма аудио и видео данных кажется не очень сложной. Я бы попробовал в ближайшее время просто слать udp-пакеты с несжатыми данными видео и аудио и простой метаинформацией (номер пакета, таймстемп, разрешение картинки и т.п.) . Это позволит собрать что-то минимально рабочее с реально небольшими тркдозатрами. После этого можно уже подумать над какими-нибудь способами сжатия информациями и более сложными стратегиями доставки.

**Comment by m-malikov** [comment]
https://gist.github.com/m-malikov/219c1728acdd44af45584b64ebb559ff
